version: '2'

services:
  camunda-exporter:
    image: docker.consulting.camunda.com/prometheus-camunda-exporter:latest
    ports:
      - "8088:8080"
    environment:
      - DB_URL=REPLACE_DB_URL
      - DB_USERNAME=REPLACE_DB_USERNAME
      - DB_PASSWORD=REPLACE_DB_PASSWORD
      - JAVA_OPTS=-Xmx128m
    restart: always
    networks:
      - camunda-exporter
    mem_limit: 650M

networks:
  camunda-exporter:
